version: '3'

services:
  nginx:
    container_name: nginx
    build: ./req/nginx
    image: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    build:          ./req/mariadb
    image:          mariadb
    restart: always
    env_file:
      - .env
    volumes:
      -  mariadb:/var/lib/mysql

    
volumes:
  mariadb:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: volume
      device: /home/adel-cor/data/db/
      o: bind
          
  wordpress:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: volume
      device: /home/adel-cor/data/wp/
      o: bind
          


          

